version: '3.7'


services:
  app:
    image: 'xd:latest'
    build:
      context: .
    container_name: app
    environment:
      - DB_HOST=postgres
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=lotto
      - POSTGRES_PASSWORD=lotto
      - POSTGRES_DB=lotto
    ports:
      - '5432:5432'
  localstack:
    image: localstack/localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=${SERVICES- s3,lambda,serverless,sqs}
      - DEBUG=${DEBUG- }
      - DATA_DIR=${DATA_DIR- }
      - PORT_WEB_UI=${PORT_WEB_UI- }
      - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR- }
      - KINESIS_ERROR_PROBABILITY=${KINESIS_ERROR_PROBABILITY- }
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"

