version: '3.7'


services:
  app:
    image: 'koniecv2:latest'
    build:
      context: .
    container_name: app
    depends_on:
      - localstack
    ports:
      - '8081:8081'
    environment:
      - DB_HOST=postgres
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=lotto
      - POSTGRES_PASSWORD=lotto
      - POSTGRES_DB=lotto
    ports:
      - '5432:5432'

  localstack:
    image: localstack/localstack:0.12.12
    ports:
      - 4566:4566
    hostname: localstack
    environment:
      - SERVICES=s3,lambda,serverless,sqs
      - AWS_DEFAULT_REGION=eu-central-1
      - EDGE_PORT=4566
      - DOCKER_HOST=unix:///var/run/docker.sock
      - HOSTNAME_EXTERNAL=localstack
      - LAMBDA_DOCKER_NETWORK=docker_default
    volumes:
      - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"

